name: helpers
description: QuadOS Helper Package
version: 1.0.0
repository: https://github.com/quad-linux/helpers
publish_to: none

environment:
    sdk: ^3.4.2

dependencies:
    cli_spin: ^1.0.1
    fast_immutable_collections: ^10.2.4
    io: ^1.0.4
    models:
        git: https://github.com/Quad-Linux/models
    path: ^1.9.0
    xdg_directories: ^1.0.4

dev_dependencies:
    lints: ^4.0.0
    test: ^1.24.0
