name: helpers
description: QuadOS Helper Package
version: 1.0.0
repository: https://github.com/quad-linux/helpers

environment:
    sdk: ^3.4.2

dependencies:
    cli_spin: ^1.0.1

dev_dependencies:
    lints: ^3.0.0
    test: ^1.24.0
